services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command:
      - start
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Hostname MUST be explicitly set in production mode
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge

    ports:
      - "8080:8080"

    volumes:
      - ./keycloak/import:/opt/keycloak/data/import

    networks:
      - keycloak_net

  postgres-keycloak:
    image: postgres:16
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
      POSTGRES_DB: keycloak

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - keycloak_net

networks:
  keycloak_net:

volumes:
  pgdata:
