services:
  # -------------------------
  # Keycloak (Auth)
  # -------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command:
      - start
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge

    ports:
      - "8080:8080"

    volumes:
      - ./keycloak/import:/opt/keycloak/data/import

    networks:
      - keycloak_net
      - backend_net

  postgres-keycloak:
    image: postgres:16
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
      POSTGRES_DB: keycloak

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - keycloak_net

  # -------------------------
  # TimescaleDB (Metrics)
  # -------------------------
  timescaledb:
    image: timescale/timescaledb:2.15.1-pg16
    environment:
      POSTGRES_USER: nodesense
      POSTGRES_PASSWORD: nodesensepass
      POSTGRES_DB: nodesense

    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

    networks:
      - backend_net
      - monitoring_net

    ports:
      - "5432:5432"

  # -------------------------
  # Collector (FastAPI)
  # -------------------------
  collector:
    build: ./collector
    image: nodesense-collector:latest

    environment:
      DB_HOST: timescaledb
      DB_USER: nodesense
      DB_PASS: nodesensepass
      DB_NAME: nodesense
      DB_PORT: 5432

    ports:
      - "3000:3000"

    networks:
      - backend_net
      - monitoring_net

    deploy:
      replicas: 2

  # -------------------------
  # Node Agent
  # -------------------------
  agent:
    build: ./agent
    image: nodesense-agent:latest
    environment:
      COLLECTOR_URL: http://collector:3000/ingest
      NODE_ID: "infrastructure-monitor"
      INTERVAL: "5"
    networks:
      - monitoring_net
    deploy:
      mode: global

  # -------------------------
  # Prometheus
  # -------------------------
  redis:
    image: redis:alpine
    networks:
      - backend_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:v2.51.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring_net
    deploy:
      replicas: 1

  # -------------------------
  # Grafana
  # -------------------------
  grafana:
    image: grafana/grafana:10.4.1
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring_net
      - backend_net
    deploy:
      replicas: 1

  # -------------------------
  # API Gateway
  # -------------------------
  gateway:
    image: nodesense-gateway:latest
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://redis:6379
      COLLECTOR_URL: http://collector:3000
      KEYCLOAK_URL: http://keycloak:8080
      REALM: NodeSense
      DB_HOST: timescaledb
      DB_USER: nodesense
      DB_PASS: nodesensepass
      DB_NAME: nodesense
      RATE_LIMIT: "100"
    networks:
      - backend_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # -------------------------
  # Alerting Service
  # -------------------------
  alerting:
    build: ./alerting
    image: nodesense-alerting:latest
    environment:
      DB_HOST: timescaledb
      DB_USER: nodesense
      DB_PASS: nodesensepass
      DB_NAME: nodesense
      CHECK_INTERVAL: "10"
    networks:
      - monitoring_net
      - backend_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # -------------------------
  # Frontend UI
  # -------------------------
  frontend:
    build: ./frontend
    image: nodesense-frontend:latest
    ports:
      - "3002:3000"
    deploy:
      replicas: 1
    networks:
      - backend_net

# -------------------------
# Networks
# -------------------------
networks:
  keycloak_net:
  backend_net:
  monitoring_net:

# -------------------------
# Volumes
# -------------------------
volumes:
  pgdata:
  timescale_data:
  prometheus_data:
  grafana_data:
