services:
  # -------------------------
  # Keycloak (Auth)
  # -------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command:
      - start
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge

    ports:
      - "8080:8080"

    volumes:
      - ./keycloak/import:/opt/keycloak/data/import

    networks:
      - keycloak_net
      - backend_net

  postgres-keycloak:
    image: postgres:16
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
      POSTGRES_DB: keycloak

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - keycloak_net

  # -------------------------
  # TimescaleDB (Metrics)
  # -------------------------
  timescaledb:
    image: timescale/timescaledb:2.15.1-pg16
    environment:
      POSTGRES_USER: nodesense
      POSTGRES_PASSWORD: nodesensepass
      POSTGRES_DB: nodesense

    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

    networks:
      - backend_net
      - monitoring_net

    ports:
      - "5432:5432"

  # -------------------------
  # Collector (FastAPI)
  # -------------------------
  collector:
    build: ./collector
    image: nodesense-collector:latest

    environment:
      DB_HOST: timescaledb
      DB_USER: nodesense
      DB_PASS: nodesensepass
      DB_NAME: nodesense
      DB_PORT: 5432

    ports:
      - "3000:3000"

    networks:
      - backend_net
      - monitoring_net

    deploy:
      replicas: 2

# -------------------------
# Networks
# -------------------------
networks:
  keycloak_net:
  backend_net:
  monitoring_net:

# -------------------------
# Volumes
# -------------------------
volumes:
  pgdata:
  timescale_data:
