{
 "title": "NodeSense Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_metric, node_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_metric{name=\"cpu_usage\", node_id=~\"$node\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_metric{name=\"mem_used\", node_id=~\"$node\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_metric{name=\"disk_percent\", node_id=~\"$node\"}",
     "legendFormat": "Disk Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Memory Saturation %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_metric{name=\"mem_used\", node_id=~\"$node\"} / ignoring(name) node_metric{name=\"mem_total\", node_id=~\"$node\"} * 100",
     "legendFormat": "Mem % - {{node_id}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_metric{name=\"net_bytes_recv\", node_id=~\"$node\"}[1m])",
     "legendFormat": "Inbound ({{node_id}})"
    },
    {
     "expr": "rate(node_metric{name=\"net_bytes_sent\", node_id=~\"$node\"}[1m])",
     "legendFormat": "Outbound ({{node_id}})"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_metric{name=\"process_count\", node_id=~\"$node\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  }
 ]
}